import "./globals.css";
import styles from "./page.module.css";
import Header from "../components/Header/header";
import Footer from "../components/Footer/footer";

export const metadata = {
  title: "Temperamentos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        <div className={styles.page}>
          <main className={styles.main}>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
